# Generated by Django 5.0.2 on 2025-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='model_type',
            field=models.CharField(choices=[('new', 'New Model'), ('old', 'Old Model')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
